trigger:
  branches:
    include:
      - chore/add-azure-pipeline

pr: none

variables:
  - group: release-pipelines-library
  - name: BUILD_DIR
    value: $(Build.ArtifactStagingDirectory)/builds
  - name: REPO
    value: ClearSale/LivenessReactNativePlugin

stages:
  - stage: release
    variables:
      - group: cs-kv-prd-core
    jobs:
      - deployment: release
        pool:
          name: AgentLinuxPrd
        environment: FACETEC-PRD
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  persistCredentials: true

                - script: |
                    git fetch --tags
                    git tag | grep -v -x -f <(git ls-remote --tags origin | awk -F/ '{print $NF}') | xargs git tag -d
                  displayName: 'Clean git TAGs'

                - task: NodeTool@0
                  inputs:
                    versionSpec: '20.x'
                  displayName: 'Install Node.js'

                - script: |
                    .yarn/releases/yarn-3.6.1.cjs install && .yarn/releases/yarn-3.6.1.cjs prepare
                  displayName: 'Build'

                - script: |
                    export GITHUB_TOKEN=$GITHUB_TOKEN
                    export NPM_TOKEN=$NPM_TOKEN

                    .yarn/releases/yarn-3.6.1.cjs release --ci
                  env:
                    GITHUB_TOKEN: $(GITHUB_TOKEN)
                    NPM_TOKEN: $(SEC-NPM-TOKEN-TECHLABS-STUDIO-SDK)
                  displayName: 'Run Release-It'
